#!/bin/sh

export PATH="$PATH:/usr/local/opt/node@20/bin"
echo $0
echo $PATH
if test -f "/etc/os-release"; then
    if grep 'ID=nixos' /etc/os-release >/dev/null; then
        PATH="$(echo "$PATH" | sed -e 's@:node_modules/.bin@@g' -e 's@node_modules/.bin:@@g')" biome check --write ./services
    fi
else
    npx @biomejs/biome check --write ./services
fi